---
version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: project-server
    container_name: server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - project-network
  mongo:
    image: mongo
    container_name: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: REDACTED
      MONGO_INITDB_ROOT_PASSWORD: REDACTED
    volumes:
      - ./testing/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - project-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: project-client
    container_name: client
    command: yarn start
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - project-network

networks:
  project-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local